# invoke the dockerfile to build the image
version: '3.8'

services:
  nginx:
    build: /Nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/usr/share/nginx/html
    networks:
      - my-network
    restart: always

  express:
    build: /Express
    networks:
      - my-network
    restart: always

  flask:
    build: /Flask
    networks:
      - my-network
    restart: always

  load_test:
    build: /LoadTest
    ports:
      - "8080:8080"
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge